// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOYS9SrAykd3KnXWQuNPpwEifIm4yL0Nk',
    appId: '1:1006469940051:web:b906be374fc3cffec857a6',
    messagingSenderId: '1006469940051',
    projectId: 'twitter-app-90e66',
    authDomain: 'twitter-app-90e66.firebaseapp.com',
    storageBucket: 'twitter-app-90e66.firebasestorage.app',
    measurementId: 'G-HPKL82LV86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqbRlgKVUOPoWZszMXXXgfuPPJwMV5KE',
    appId: '1:1006469940051:android:becbee69879fe2f7c857a6',
    messagingSenderId: '1006469940051',
    projectId: 'twitter-app-90e66',
    storageBucket: 'twitter-app-90e66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJnysHG8G26vBKUPhem_YVCZ_repK9tU0',
    appId: '1:1006469940051:ios:511c9eb209819c63c857a6',
    messagingSenderId: '1006469940051',
    projectId: 'twitter-app-90e66',
    storageBucket: 'twitter-app-90e66.firebasestorage.app',
    iosBundleId: 'com.example.twitterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJnysHG8G26vBKUPhem_YVCZ_repK9tU0',
    appId: '1:1006469940051:ios:511c9eb209819c63c857a6',
    messagingSenderId: '1006469940051',
    projectId: 'twitter-app-90e66',
    storageBucket: 'twitter-app-90e66.firebasestorage.app',
    iosBundleId: 'com.example.twitterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOYS9SrAykd3KnXWQuNPpwEifIm4yL0Nk',
    appId: '1:1006469940051:web:a45a5775cc7a5d31c857a6',
    messagingSenderId: '1006469940051',
    projectId: 'twitter-app-90e66',
    authDomain: 'twitter-app-90e66.firebaseapp.com',
    storageBucket: 'twitter-app-90e66.firebasestorage.app',
    measurementId: 'G-J9YKTPY7G8',
  );
}
